export const SVGS = {
  face: {
    '0': require('assets/svg/face/0.svg'),
    '1': require('assets/svg/face/1.svg'),
    '2': require('assets/svg/face/2.svg'),
    '3': require('assets/svg/face/3.svg'),
    '4': require('assets/svg/face/4.svg'),
    '5': require('assets/svg/face/5.svg'),
    '6': require('assets/svg/face/6.svg'),
    '7': require('assets/svg/face/7.svg'),
    '8': require('assets/svg/face/8.svg'),
    '9': require('assets/svg/face/9.svg'),
    a: require('assets/svg/face/a.svg'),
    b: require('assets/svg/face/b.svg'),
    c: require('assets/svg/face/c.svg'),
    d: require('assets/svg/face/d.svg'),
    e: require('assets/svg/face/e.svg'),
    f: require('assets/svg/face/f.svg'),
  },
  head: {
    '0': require('assets/svg/head/0.svg'),
    '1': require('assets/svg/head/1.svg'),
    '2': require('assets/svg/head/2.svg'),
    '3': require('assets/svg/head/3.svg'),
    '4': require('assets/svg/head/4.svg'),
    '5': require('assets/svg/head/5.svg'),
    '6': require('assets/svg/head/6.svg'),
    '7': require('assets/svg/head/7.svg'),
    '8': require('assets/svg/head/8.svg'),
    '9': require('assets/svg/head/9.svg'),
    a: require('assets/svg/head/a.svg'),
    b: require('assets/svg/head/b.svg'),
    c: require('assets/svg/head/c.svg'),
    d: require('assets/svg/head/d.svg'),
    e: require('assets/svg/head/e.svg'),
    f: require('assets/svg/head/f.svg'),
  },
};
